### PR TITLE
Information and assets

### PR DESCRIPTION
**Pull request by Dhriti-Roy**
LocalHackDay Assets

### CODE REVIEW

**Comment by adityaraute** [comment]
Consider removing the fields from the description that are not being used, and instead write a simple single line description of the PR.

**Comment by eddiejaoude** [comment]
@Dhriti-Roy don't forget to add yourself to the main readme (`README.md` in the root of the project)

**Comment by Dhriti-Roy** [comment]
Okay @dumbcoder7

**Comment by Dhriti-Roy** [comment]
Sure @eddiejaoude .

**Comment by adityaraute** [comment]
There seems to be some conflicts. Can you look into them more closely?

**Comment by Dhriti-Roy** [comment]
Now, I think there are no  more conflicts.

**Review by adityaraute — APPROVED** [review]

**Comment by eddiejaoude** [comment]
Thank you @Dhriti-Roy and @adityaraute 👍

**Pull request merged**
