### PR TITLE
Added Name and Repo Links 

### PR DESCRIPTION
**Pull request by saumya66**
Fixes #5

### CODE REVIEW

**Comment by adityaraute** [comment]
Please edit the PR description to only have points that are necessary for the PR.

**Comment by saumya66** [comment]
> Please edit the PR description to only have points that are necessary for the PR.

Any Suggestion

**Comment by adityaraute** [comment]
> Title: Added Name and Repo Links

> Description: I have added my name in the readme file as well as linked all the repos created during MLH LHD:Build

**Comment by saumya66** [comment]
> > Title: Added Name and Repo Links
> 
> > Description: I have added my name in the readme file as well as linked all the repos created during MLH LHD:Build

Is that okay?

**Review by eddiejaoude — APPROVED** [review]
Looks good 👍

**Comment by eddiejaoude** [comment]
Thank @dumbcoder7 for reviewing 👍 . @saumya66 not sure about the heading font used for the description - needs some work, do more for practice 😉

**Comment by saumya66** [comment]
> Thank @dumbcoder7 for reviewing 👍 . @saumya66 not sure about the heading font used for the description - needs some work, do more for practice 😉

Sure , Thanks ! @eddiejaoude  & @dumbcoder7

**Pull request merged**
