### PR TITLE
Added asset

### PR DESCRIPTION
**Pull request by adityaraute**
Added the image of my MSPaint challenge from Local Hack Day

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Do you want to link to the image and display it?

**Comment by eddiejaoude** [comment]
@adityaraute I can merge as it is, but a link might make it more discoverable

**Comment by adityaraute** [comment]
How? I am not sure where to put the image for the link? Should I have the image in the folder, and then link in the Readme?

**Comment by eddiejaoude** [comment]
@kcoder63 put a README in the assets folder to show the previews of the images, then in main README under Karuna's section put a link to the folder, this seems to work well

- https://github.com/EddieJaoudeCommunity/Hackathons#karuna-tata
- https://github.com/EddieJaoudeCommunity/Hackathons/tree/main/2021/01/localhackday/kcoder63

**Comment by adityaraute** [comment]
Okay will definitely do this.

**Comment by adityaraute** [comment]
Sorry for multiple commits. Did the needful.

**Comment by eddiejaoude** [comment]
No problem, I can squash them 🤓

**Review by eddiejaoude — COMMENTED** [review]
LGTM

**Pull request merged**
