### PR TITLE
Fixed a typo

### PR DESCRIPTION
**Pull request by adityaraute**
'January' was spelt wrong. Fixed it.

### CODE REVIEW

**Review by eddiejaoude — APPROVED** [review]
Thank you!

**Comment by adityaraute** [comment]
The checks haven't finished yet though 😂

**Comment by eddiejaoude** [comment]
I trusted you :). Btw I am not sharing this repo in Discord yet, until 1 or 2 people I have asked fill it in, so we can work out any tweaks needed to the docs etc. Then we can share and get more people to add their info

**Comment by adityaraute** [comment]
Sounds valid.

**Pull request merged**
