### PR TITLE
Added links to my projects built during LHD: Build 2021

### PR DESCRIPTION
**Pull request by Utkarsh299-tech**

### CODE REVIEW

**Review by AllanRegush — COMMENTED** [review]
I think we should remove the binary images. If you want make an issue and paste the image into the issue and put the link in the readme. Side Note - Maybe we should ask everyone to put their hackathon art in therir own repo and add the link. @eddiejaoude what are your thoughts?

**Comment by AllanRegush** [comment]
> 
> 
> I think we should remove the binary images. If you want make an issue and paste the image into the issue and put the link in the readme. Side Note - Maybe we should ask everyone to put their hackathon art in therir own repo and add the link. @eddiejaoude what are your thoughts?

I see that kcoder63 has done something similar

**Comment by eddiejaoude** [comment]
I agree with you for normal repos, but this repo is something we will all be pushing/pulling from, so less of an issue. I am happy with whatever is easier for people to add their projects.

**Review by AllanRegush — APPROVED** [review]
👍 Eddie's comment is good enough for me.

**Review by eddiejaoude — APPROVED** [review]
Thank you 👍

**Comment by Utkarsh299-tech** [comment]
> Thank you 👍

Thank you @AllanRegush and @eddiejaoude :)

**Pull request merged**
