### PR TITLE
Add Kaiwalya Koparkar

### PR DESCRIPTION
**Pull request by kaiwalyakoparkar**
## Proposed Changes

  - Added my lhd assets
  - added my projects in the readme
  - updated readme with the link to my assets

### CODE REVIEW

**Comment by eddiejaoude** [comment]
Should these go in the other folder? https://github.com/EddieHubCommunity/Hackathons/tree/main/2021/03/localhackday

**Comment by kaiwalyakoparkar** [comment]
Should I shift them there?

**Comment by eddiejaoude** [comment]
yes please

**Comment by kaiwalyakoparkar** [comment]
Ok, I will just close this PR as I messed up with my local fork. I will raise new PR with required changes.

**Pull request closed without merging**
